name: manto_bride
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  get_it: ^8.0.0
  equatable: ^2.0.5
  logger: ^2.3.0
  flutter_onboarding_slider: ^1.0.11
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  dropdown_button2: ^2.3.9
  animated_splash_screen: ^1.3.0
  flutter_carousel_widget: ^3.0.1
  cached_network_image: ^3.3.1
  bottom_sheet: ^4.0.4
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  rate_in_stars: ^0.0.3
  confetti: ^0.8.0
  firebase_core: ^3.5.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.1.6
  permission_handler: ^11.3.1
  email_validator: ^3.0.0
  lottie: ^3.1.2
  video_player: ^2.9.1
  flick_video_player: ^0.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  azlistview: ^2.0.0
  flutter_typeahead: ^4.8.0
  share_plus: ^10.0.2
  # path_provider: ^2.1.4
  # youtube_player_flutter_quill: ^8.2.2
  # youtube_player_flutter: ^9.0.3
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.0
  # sweet_nav_bar: ^1.0.5
  # flutter_floating_bottom_bar: ^1.2.1+1
  flex_list: ^1.0.0
  flutter_local_notifications: ^18.0.1
  flutter_inappwebview: ^6.1.5
  intl_phone_field: ^3.2.0
  widget_zoom: ^0.0.4
  flutter_tap_payment: ^0.2.1
  restart_app: ^1.3.2
  # flutter_facebook_auth: ^7.0.1
  # flutter_typeahead: ^5.2.0
  # share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

  
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/ar.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-Bold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-Bold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Bold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Black.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-Medium.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-Medium.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-Medium.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Medium.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-SemiBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-SemiBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-SemiBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-Black.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-Black.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-Light.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-Black.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-BlackItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-BlackItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-BlackItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-BoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-BoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-ExtraBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-ExtraBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-ExtraLight.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-ExtraLight.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-ExtraLight.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_7pt_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_Expanded-SemiBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans_10pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans1 (1).ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans1 (2).ttf
       